site_name: Lazy Guide
site_url: https://xelieu.github.io/
site_description: JP Immersion Tool Lazy Guide
site_author: Xelieu
repo_url: https://ko-fi.com/xelieu
repo_name: Want to buy me a coffee?
nav:
  - Home:
    - Introduction: 'jp-lazy-guide/index.md'
    - Changelog (2023-08-05): 'jp-lazy-guide/changelog.md'
    - About: 'jp-lazy-guide/about.md'
    - Credits: 'jp-lazy-guide/credits.md'
  - Setup:
    - Setup Introduction: 'jp-lazy-guide/setup.md'
    - Essentials:
      - "Setup: Anki": 'jp-lazy-guide/setupAnki.md'
      - "Setup: Yomichan PC": 'jp-lazy-guide/setupYomichanOnPC.md'
      - "Setup: Yomichan Android": 'jp-lazy-guide/setupYomichanOnAndroid.md'
      - "Setup: ShareX": 'jp-lazy-guide/setupShareX.md'
    - Visual Novel:
      - "Setup: VN on PC": 'jp-lazy-guide/setupVnOnPC.md'
      - "Setup: VN on Android": 'jp-lazy-guide/setupVnOnAndroid.md'
    - Light Novel:
      - "Setup: LN on PC": 'jp-lazy-guide/setupLnOnPC.md'
      - "Setup: LN on Android": 'jp-lazy-guide/setupLnOnAndroid.md'
    - Manga:
      - "Setup: Manga on PC": 'jp-lazy-guide/setupMangaOnPC.md'
      - "Setup: Manga on Android": 'jp-lazy-guide/setupMangaOnAndroid.md'
    - Anime:
      - "Setup: Anime on PC": 'jp-lazy-guide/setupAnimeOnPC.md'
      - "Setup: Anime on Android": 'jp-lazy-guide/setupAnimeOnAndroid.md'
    - Miscellaneous:
      - "Transfer Lazy Setup to JPMN": 'jp-lazy-guide/transferAnkiSetup.md'
  - Sub Guide:
    - Sub Guide Introduction: 'jp-lazy-guide/subGuide.md'
    - Concise Guide to Jumpstart JP: 'jp-lazy-guide/conciseGuideToJumpstartJP.md'
    - Retention How-To: 'jp-lazy-guide/retentionHowTo.md'
  - Resources: 
    - Resources Introduction: 'jp-lazy-guide/resources.md'
    - Immersion Data Spreadsheet: 'jp-lazy-guide/immersionDataSpreadsheet.md'
    - Deck Resources: 'jp-lazy-guide/resourcesDecks.md'
theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon-2.png
  icon:
    repo: simple/buymeacoffee
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: indigo
      accent: indigo

extra:
  homepage: https://xelieu.github.io/jp-lazy-guide/
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Xelieu
      name: Github - Xelieu
    - icon: fontawesome/brands/discord
      link: https://www.discordapp.com/users/719459399168426054
      name: Discord - xelieu
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@xelieu
      name: Youtube - Xelieu      
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/xelieu
      name: Ko-Fi - Xelieu
  analytics:
    provider: google
    property: G-GMJZ3SM36S
  generator: false
  
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - git-revision-date-localized
  - search:
      lang:
        - en
        - ja

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/Xelieu/xelieu.github.io/blob/main/LICENSE"  target="_blank" rel="noopener">Xelieu</a>